language: node_js
node_js: 12.17.0
branchs:
    only:
        - master
install:
    - yarn
script:
    - npm run lint
    - npm run build
# after_success:
#     - npm run coverage
deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: master
    script:
        - npm run release
cache:
    directories:
        - node_modules
notifications:
    webhooks:
        urls:
            # 钉钉
            - secure: pCBLuzxjzjdLTHZhse4z66lQJsyrklML1lPfwZSQfgBJLMteyrY9bXqH0uXxzw7UpnFvFQRZjOanDQh+78M1U43PoXzGzONcRc8FTMOSGgCiLd7w7ZNaKaBP+uCzvnS2Y0uHZpZcb0QxCvLTBMQGpO6NztcDTYAoVmWtok0/IwNdHI45Bh4kefNT5L9WE2M09R9J7dLI42feHzNyf7iSHEEJTOi7V5v++FdnRzdA+Vy/UtESpN4RviAJ4E/FXMQhuJ6ili9w/P4qPBJyMTtn9XxRmkSXP+UIwWNoojl/UcbnAKFVywcQzQkyfqe4grz1xmeyoSDX/PopMwpok+/N7pBY4/UWz8k16GlISOifME5MfZ/SHhP5BS/yYV5Pih8iHwMaM0gqXIo2nuBVdBF7pB3058zbIovM0v2FSg3wV2z+4PLeS4UsWaxt5Iqpq0YoWvkOmCMB8aqP1acqCKplkqNw3sU3WJ7mIU8xTd9U5PPYGHeF86h+BLMdz8nYHI8n8n1muKUMaW8MZ4G7jLlOX31Fx07VVjAOAhj0rWAz9qVOKjZFhFh+HmaBgY84zR6zQzZnNtD42vsaNrbKkXsOIrc7cSDdAkkM/7xUeOl+Y0Inr5ElALTpKz5oem7P0M1AN2Z/IAYVYuI9Sre0uFEsbnPbGZ54c7s5/k2r4WFztMk=
            # jenkins
            # - secure: dzEw88cbYm55iZknUGWkny226YyHB+c5KRSlEgTYWQVmsR4cwAqyrDGrtuEDnVQOCFeX/vJHoMqU/9/ZYj5i4tI7DYBF2qRYITxdAxXraXlGQuKhOXZPxJjUYklWz8bd3NH7lCO9gvwwxynxEkW6zEcn/31tsoI7XaKF14k7z0YZ+1z61RKAsZT75td+L/nTz7XbUjGGKfETRscEI1FfUBovzoJN1Xoou80zDfOPzLwjgUoWMzPviEJ+TqVZijWvrjW4G2lXM0sY3HvG0otfxcQoejbp2cPQXHcRnFuOOvsPeRuI2TVrref+siPHo1Ln8UAjcIIcKnrPgXmPHAHvQ5XxYaKdjz8FfTS7IDTUJ27vpsRGcRr5NhmOsJHhSWrXui+z+yA+fYnd/NYAlJU73tcPji8MOSGryGGxtg6jStlOb1aDXaX6Z2zH7+O7FZbZzSNAlMhfv/iByitcHKEPDAr88pR8ejdZwkxl7PS6c95NQzHyKmSGG8IS7aTK9Lg8PQtoIqI2I8Ve7gm/KlCRymDX8W7Y7OlDXcv6RClKhax1P1aVQAZKxZGgrRzhzQz0eYbFD1WZ1mBBLgJn+fKIhiSJ/DwYlgCoQIzXPtW+y2FjwPuFPWFwfYT0NM0vFjpB8Qt8LaY8sUzryJ0r6HIopYvOlUJ8lH39dnBPRe+L8Ug=
        on_success: always # default: always
        on_failure: always # default: always
        on_start: always # default: never change
        on_cancel: always # default: always
        on_error: always
